import { MASTER_PATTERN_FAMILIES, MASTER_PATTERN_COMBINATIONS } from "./masterCatalog";

export const ALL_PATTERN_FAMILIES = MASTER_PATTERN_FAMILIES;
export const ALL_PATTERN_COMBINATIONS = MASTER_PATTERN_COMBINATIONS;

export * from "./masterCatalog";
